
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      GROQ_KEY: ${{ secrets.GROQ_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Run deploy script
        run: python fooddelivery/hosting/hosting.py
