
name: Food Delivery Chatbot MLOps Pipeline

on:
  push:
    branches:
      - main  # Automatically triggers on push to the main branch

jobs:
  deploy-hosting:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r Food-Delivery-Chatbot/requirements.txt
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Food-Delivery-Chatbot/hosting/hosting.py
